#!/usr/bin/env Rscript
# Example: Create Machine Learning Article using OpenCode R SDK
# This script demonstrates how to use the SDK to generate content
# and save it as a markdown file

library(opencode)
library(cli)

# Configuration
BASE_URL <- "http://localhost:51769"
MODEL_ID <- "glm-4.7"
PROVIDER_ID <- "zai-coding-plan"
OUTPUT_FILE <- "machine_learning_intro.md"

cat("\n")
cat("========================================\n")
cat("OpenCode R SDK - Content Generation\n")
cat("========================================\n\n")

# Create client
cli::cli_h1("Creating Opencode Client")
client <- Opencode$new(
  base_url = BASE_URL,
  timeout = 180,
  max_retries = 3
)
cli::cli_alert_success("Client created!\n")

# Create a new session
cli::cli_h2("Creating Session")
session <- client$session$create()
cli::cli_text("Session ID: {session$id}")
cli::cli_text("Session slug: {session$slug}\n")

# Generate content about machine learning
cli::cli_h2("Generating Machine Learning Content")
cli::cli_text("Asking {MODEL_ID} to explain machine learning...\n")

response <- client$session$chat(
  id = session$id,
  model_id = MODEL_ID,
  provider_id = PROVIDER_ID,
  parts = list(
    list(
      type = "text",
      text = "Write a short 300-word introduction to machine learning in markdown format.
Include these sections:
## What is Machine Learning?
## Types of ML
## Common Uses
Keep it simple and beginner-friendly."
    )
  )
)

cli::cli_alert_success("Response received!\n")

# Extract the content
ml_content <- response$content
cli::cli_h2("Generated Content Preview")
cli::cli_text("{substring(ml_content, 1, 200)}...\n")

# Add front matter to the markdown
markdown_content <- paste0(
  "---\n",
  "title: \"Introduction to Machine Learning\"\n",
  "author: \"Generated by OpenCode R SDK\"\n",
  "date: \"", Sys.Date(), "\"\n",
  "model: \"", MODEL_ID, "\"\n",
  "provider: \"", PROVIDER_ID, "\"\n",
  "---\n\n",
  ml_content,
  "\n\n---\n*Generated using OpenCode R SDK with ", MODEL_ID, " from ", PROVIDER_ID, "*"
)

# Save to markdown file
cli::cli_h2("Saving to Markdown")
writeLines(markdown_content, OUTPUT_FILE)
cli::cli_alert_success("Content saved to: {OUTPUT_FILE}\n")

# Get session messages for history
cli::cli_h2("Session Messages")
messages <- client$session$messages(session$id)
cli::cli_text("Total messages in session: {length(messages$messages %||% 0)}\n")

# Clean up - delete the session
cli::cli_h2("Cleanup")
delete_result <- client$session$delete(session$id)
cli::cli_alert_success("Session deleted!\n")

# Summary
cli::cli_h1("Complete!")
cli::cli_text("Generated machine learning introduction saved to: {OUTPUT_FILE}")
cli::cli_text("Run 'cat {OUTPUT_FILE}' to view the content")

cat("\n========================================\n")
cat("Execution Complete\n")
cat("========================================\n\n")
